---
- name: Configure RHEL 8 with WebLogic 14c domain
  hosts: all
  become: true
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  roles:
    #- role: linux-wls
    - role: linux-jdk
    - role: fmw-software
   